---
title: "Lab 2"
author: "Sofia Garrick 04/16/20"
output: pdf_document
---
# Data

energy data source: Independent Statistics & Analysis: U.S. Energy Information Administration [link](https://www.eia.gov/electricity/data.php)

shape file source: US Census [link](https://catalog.data.gov/dataset/tiger-line-shapefile-2017-nation-u-s-current-state-and-equivalent-national)

```{r, echo = FALSE}
library(sf)
library(sp)
library(dplyr)
library(ggplot2)
library(stringr)
```

### Load Data
```{r, warning = FALSE}
data = read.csv("/cloud/project/test.csv", stringsAsFactors = FALSE)

data_en = data %>%
  mutate(consumptionnum = as.numeric(consumption))

shape = st_read("/cloud/project/us_boundaries_updated.shp")
shape_new = shape %>%
  rename(STATE=STUSPS)
```

# CLEANING THE DATA

### generate clean csv
```{r, warning = FALSE}
totconsumption = data_en %>%
  group_by(YEAR, STATE) %>%
  summarize(tot = sum(consumptionnum))

setwd("/cloud/project/")
write.csv(x = totconsumption, file = "energy_usage1.csv")
```

### connect spatial data
```{r, warning = FALSE}
energy = read.csv("/cloud/project/energy_usage.csv")
energy_shp = left_join(shape_new, energy)
```

# EXPLORING THE DATA: summary stats

### What is the change in energy consumption from 2000 to 2015? 

```{r}
changed = energy_shp %>% 
  mutate(change = tot_2015-tot_2000) %>%
  top_n(n=-10, wt = change)

ggplot(changed, aes(x=STATE, y=change, fill=STATE))+
geom_bar(stat="identity", color="black")+ ggtitle("Change in Energy Consumption from 2000 to 2015") + labs(y = "Change in Energy Consumption", x = "State") + theme(plot.title=element_text(family="Courier", face="bold", size=20), legend.title = element_blank(), axis.text.x=element_blank(), legend.text = element_text(family= "Courier", size = 10), axis.title =element_text(family= "Courier", size = 12)) 
```

# MAPPING THE DATA

### map of change in energy consumption from year 2000 to year 2015

```{r}
allchange = energy_shp %>% 
  mutate(change = tot_2015-tot_2000,
         changep = (tot_2015-tot_2000) * 1/100000) 

plot(allchange["changep"],xlim= c(-175, -50) ,ylim=c(20, 70), main = "Change in Energy Consumption", cex.main = 1, key.pos = 1, key.width = lcm(1.3), key.length = 1.0, breaks = "quantile")
```
